### PR TITLE
Fix conflict

### PR DESCRIPTION
**Pull request by hermawan22**
Tp kenapa warna svgnya jadi pink yah?
Wkwkwkwk

### CODE REVIEW

**Comment by hermawan22** [comment]
Coba di review dulu om @herpiko

**Comment by herpiko** [comment]
Warnanya gak kontras

screen shot 2017-09-17 at 11 11 59 pm

screen shot 2017-09-17 at 11 12 03 pm

**Comment by herpiko** [comment]
Mesti keluarga Arial.

screen shot 2017-09-17 at 11 11 52 pm

**Comment by herpiko** [comment]
Perlu margin di bawah.

screen shot 2017-09-17 at 11 12 18 pm

**Comment by herpiko** [comment]
Mobile view? Itu sebabnya awalnya saya pakai satu garis lurus ke bawah (lol).

screen shot 2017-09-17 at 11 12 57 pm

screen shot 2017-09-17 at 11 13 04 pm

**Pull request closed without merging**
